version: '3.8'

services:
  react-app:
    build: .
    container_name: react-app-container
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
    command: ["npm", "run", "dev", "--", "--host"]
